### ISSUE TITLE
1.0.X Checklist

### ISSUE THREAD

**Issue by valoeghese** [minecraft-cursed-legacy/Cursed-Legacy-API#26]
- [x] Modularise the API, like fabric does.
- [x] Remap the other tile arrays (Fixes #25)
- [x] Tile textures API (#18)
- [x] Make a feature gen system for decorated features, similar to modern MC, which can be run in the chunk population callback.
- [x] Make the world gen callbacks less cursed, perhaps making a World Type system
- [x] #28 RegistryEntryAddedCallback
- ~~Maybe have lossycache biome layers if fast enough~~ I'll do this later
- ~~(maybe) Json Model system in modern style. Shouldn't be too hard, just use gson from certain mod jar files and transfer model data to corelib.~~ I'll do this later probably. Scanning is not simple.
- [x] #31 

**Also Maybe**
- ~~Make extended tile IDs possible (This would serve better as a separate mod, perhaps an Official Mod however.)~~ not going in api

**Comment by valoeghese** [comment]
If there are any other majorly important things suggest them here or ping me on discord

**Comment by valoeghese** [comment]
Tile textures api? Just use corelib yeehaw

**Comment by valoeghese** [comment]
When I next have time to work on this I'll finish off the TODO stuff here. Hopefully in the meanwhile WillBL can PR the updated tile entities module to 1.0.x

**Comment by valoeghese** [comment]
merged tile entities
